name: RDBOX App Market
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SECRET_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: bash
    - name: Run main script
      run: |
        cd /script_for_rdbox_app_market
        make release-bot
      shell: bash
    - name: Show Executed Log
      run: |
        cat /tmp/rdbox_app_market.log
      shell: bash
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}