name: RDBOX App Market
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SECRET_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: bash
    - name: Setting Git account
      run: |
        git config --global user.name "rdbox-bot"
        git config --global user.email info-rdbox@intec.co.jp
      shell: bash
    - name: Run bot-gen script
      run: |
        sudo rm -rf /tmp/.original.charts
        make release-bot
      shell: bash
    - name: Run manually script
      run: |
        sudo rm -rf /tmp/.original.charts
        make release-manually
      shell: bash
    - name: Show Executed Log
      run: |
        cat /tmp/rdbox_app_market.log
      shell: bash
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}